mamlakatlar = ['O\'zbekiston', 'Rossiya', 'Belarusiya', 'Gruziya', 'Maldova', 'Germaniya']
# print(mamlakatlar)
# print(len(mamlakatlar))
# print(sorted(mamlakatlar))
# print(sorted(mamlakatlar, reverse=True))
# print(mamlakatlar)
# mamlakatlar.reverse()
# print(mamlakatlar)
# mamlakatlar.sort()
# print(mamlakatlar)
# mamlakatlar.sort(reverse=True)
# print(mamlakatlar)
numbers = list(range(120,1200,2))
# print(numbers, '120 dan 1200 gacha juft sonlar')
# print('Ularning yig\'indisi',sum(numbers),'ga teng')
# print(f'{max(numbers)} sonni va {min(numbers)} ni ayirmasi {max(numbers) - min(numbers)} ga teng')
# print('120 dan 1200 gacha juft sonlar',len(numbers), 'ta')
# print(numbers[0:20])
# print(numbers[260:-260])
# print(numbers[-21:-1])
taomlar = ['Palov', 'Somsa', 'Manti', 'Chuchvara', 'Kabob']
# nonushta = taomlar[:]
# nonushta.remove('Palov')
# nonushta.remove('Manti')
# nonushta.append('Tuxum')
# nonushta.append('Sho\'rva')
# nonushta = tuple(nonushta)
# print(taomlar)
# print(nonushta)